# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: vllm-disaggregated-default
  namespace: dynamo-system
spec:
  backendFramework: vllm
  pvcs:
    - name: dynamo-model-cache
      create: false
  services:
    Frontend:
      envFromSecret: hf-token-secret
      volumeMounts:
        - name: dynamo-model-cache
          mountPoint: /models
      envs:
        - name: HF_HOME
          value: /models
        - name: HF_HUB_CACHE
          value: /models
      componentType: frontend
      replicas: 1
      resources:
        requests:
          cpu: "2"
          memory: 4Gi
        limits:
          cpu: "2"
          memory: 4Gi
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/dynamo-frontend:1.0.1
          workingDir: /workspace/components/backends/vllm
          command:
            - /bin/sh
            - -c
          args:
            - python3 -m dynamo.frontend --http-port 8000
    VllmDecodeWorker:
      envFromSecret: hf-token-secret
      volumeMounts:
        - name: dynamo-model-cache
          mountPoint: /models
      envs:
        - name: UCX_TLS
          value: ^mm # Disable shared memory transport to avoid broadcast deadlock
        - name: HF_HOME
          value: /models
        - name: HF_HUB_CACHE
          value: /models
      componentType: worker
      subComponentType: decode
      replicas: 1
      resources:
        requests:
          cpu: "8"
          memory: 20Gi
          gpu: "2"
        limits:
          cpu: "8"
          memory: 20Gi
          gpu: "2"
      extraPodSpec:
        nodeSelector:
          karpenter.sh/nodepool: g5-nvidia
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.0.1
          workingDir: /workspace/components/backends/vllm
          command:
            - /bin/sh
            - -c
          args:
            - python3 -m dynamo.vllm --model deepseek-ai/DeepSeek-R1-Distill-Llama-8B --tensor-parallel-size 2
    VllmPrefillWorker:
      envFromSecret: hf-token-secret
      volumeMounts:
        - name: dynamo-model-cache
          mountPoint: /models
      envs:
        - name: UCX_TLS
          value: ^mm # Disable shared memory transport to avoid broadcast deadlock
        - name: HF_HOME
          value: /models
        - name: HF_HUB_CACHE
          value: /models
      componentType: worker
      subComponentType: prefill
      replicas: 1
      resources:
        requests:
          cpu: "8"
          memory: 20Gi
          gpu: "2"
        limits:
          cpu: "8"
          memory: 20Gi
          gpu: "2"
      extraPodSpec:
        nodeSelector:
          karpenter.sh/nodepool: g5-nvidia
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.0.1
          workingDir: /workspace/components/backends/vllm
          command:
            - /bin/sh
            - -c
          args:
            - python3 -m dynamo.vllm --model deepseek-ai/DeepSeek-R1-Distill-Llama-8B --disaggregation-mode prefill --kv-transfer-config '{"kv_connector":"NixlConnector","kv_role":"kv_both"}' --tensor-parallel-size 2
