apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dynamo-core
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ai-dynamo/dynamo.git
    targetRevision: ${dynamo_version}
    path: deploy/cloud/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: dynamo-cloud
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated: {}
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.template.spec.containers[].image
    - group: v1
      kind: Secret
      jqPathExpressions:
        - .data
